/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import struts.form.StrutsformForm;

public class StrtusactionAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		StrutsformForm strutsformForm = (StrutsformForm) form;
		System.out.println("用户名："+strutsformForm.getUsername());
		System.out.println("密码he："+strutsformForm.getPassword());
		request.setAttribute("strutsformForm", strutsformForm);
		System.out.println("================================");
		return mapping.findForward("reg");
	}
}